# -*- coding: utf-8 -*-
"""Salvando_Imagens_Request

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zo0qMC88CD0ILI-nAIIGAtI_lGDIvoZU
"""

import requests

url = "http://mediaphoto.mnhn.fr/media/1414683588571yBLEBHDzJeLPOmeT"
response = requests.get(url)
if response.status_code == 200:
    with open("teste.jpg", 'wb') as f:
        f.write(response.content)

